### ISSUE TITLE
isMobile shouldn't set by default

### ISSUE THREAD

**Issue by tacman** [markbrownsword/penny-pixel-2d-tilemap#19]
Anyone who downloads and tests this from their computer will run into the issue that jumping and running doesn't work, because isMobile is checked by default.

It'd be great if this were updated to use the new input system, then isMobile wouldn't even be needed.

If you're open to that, I'll update the project to 2020.1 (or 2019.4) and make a PR.

**Comment by markbrownsword** [comment]
I would appreciate an update, thanks.
